config/routes.rb
Rails.application.routes.draw do

  devise_for :customers
  devise_for :owners
  resources :places do
    collection do
            get :mine
    end

    resources :comments, only: [:create, :destroy]
    resources :reservations, only: [:create, :destroy]
  end
  resources :categories, only: [:show, :index]
  root 'places#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/category.rb
class Category < ApplicationRecord
has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :place
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, dependent: :destroy
  has_many :reservasyons
end

app/models/food.rb
class Food < ApplicationRecord
  has_and_belongs_to_many :places
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places, dependent: :destroy
end

app/models/place.rb
class Place < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :phone_number, length: { minimum: 5}
  validates :city, presence: true



  def category
    Category.find(category_id)

  end

  belongs_to :category
  belongs_to :owner
  has_many :comments, dependent: :destroy
  has_many :reservations
  has_and_belongs_to_many :foods
  has_one :social_profile


  accepts_nested_attributes_for :social_profile
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :place
end

app/models/social_profile.rb
class SocialProfile < ApplicationRecord
  belongs_to :place, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_comment, only: [:destroy]
  before_action :authorize_customer!, only: [:destroy]

  def create
    @place = Place.find(params[:place_id])
    @comment = @place.comments.new(comment_params)
    @comment.customer = current_customer

    if @comment.save
      CommentMailer.new_comment(@place).deliver_now
      redirect_to place_path(@place)
    end
  end

  def destroy
    @place = Place.find(params[:place_id])
    @comment = @place.comments.find(params[:id])
    @comment.destroy
    redirect_to place_path(@place)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def authorize_customer!
    redirect_to @place, notice: "Not authorized" unless @comment.customer_id == current_customer.id
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_owner!, except: [:show, :index]
  before_action :set_place, only: [:show, :update, :edit, :destroy]
  before_action :authorize_owner!, only: [:edit, :update, :destroy]
  def index
    @places = Place.all
  end

  def show
    set_place
  end

  def new
    @place = Place.new
    @place.build_social_profile
    load_categories
  end

  def mine
    @places = current_owner.places
  end

  def create
    @place = current_owner.places.new(place_params)

    if @place.save
      redirect_to place_path(@place)
    else
      load_categories
      render :new
    end
  end

  def edit
    set_place
    load_categories
  end

  def update
    if @place = Place.update(place_params)
      redirect_to place_path(@place)
    else
      load_categories
      render :edit
    end
  end

  def destroy
    set_place
    @place.destroy
    redirect_to places_path

  end
  private
  def load_categories
    @categories = Category.all.collect {|c| [c.name, c.id ] }
    @foods = Food.all
  end

  def set_place
    @place = Place.find(params[:id])
  end
  def place_params
    params.require(:place).permit(:name, :address, :city, :phone_number,:contact_mail,
                                  :description, :estanlished_at, :category_id, :owner_id, food_ids: [],
                                  social_profile_attributes: [:id, :facebook, :twitter, :instagram, :foursquare])
  end

  def authorize_owner!
    redirect_to @place, notice: "Not authorized" unless @place.owner_id == current_owner.id
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_place


  def create

    @reservation = @place.reservations.new(reservation_params)
    @reservation.customer = current_customer

    if @reservation.save
      redirect_to @place, notice: "reservation was saved."
    else
      redirect_to @place, notice: "reservation is not valid."
    end
  end

  def destroy
    @reservation = @place.reservations.find(params[:id])
    @reservation.destroy
    redirect_to @place
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date,:number_of_people)
  end

  def set_place
    @place = Place.find(params[:place_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/categories/index.html.erb
<h1>List of Categories</h1>
<% @categories.each do |c| %>
    <%= link_to c.name, category_path(c)%>
<% end %>

app/views/categories/show.html.erb
<h1> <%= @category.name%></h1>

<% @category.places.each do |place|%>
    <b>ID </b><%= place.id %><br>
    <b>Title </b>
    <%= link_to place.name, place_path(place) %><br>
    <b>Description </b><%= place.description %><br><hr>
<% end %>

<%=link_to "Go Back to Places", places_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">

        <a class="navbar-brand" href="#">Reservation</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


        <ul class="nav navbar-nav navbar-right">
          <% if current_owner.present? %>
              <%= link_to "My Places", mine_places_path  %>
              <%= current_owner.email %>
              <%= link_to "Log Out",  destroy_owner_session_path, method: :delete%><br><br>
          <% elsif current_customer.present? %>
              <%= current_customer.email %>
              <%= link_to "Log Out",  destroy_customer_session_path, method: :delete%><br><br>
          <% else %>
              <%= link_to "Owner Log In",  new_owner_session_path%>
              <%= link_to "Owner Sign Up",  new_owner_registration_path%>
              <%= link_to "Customer Log In",  new_customer_session_path%>
              <%= link_to "Customer Sign Up",  new_customer_registration_path%>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>





  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :phone_number %><br>
      <%= f.text_field :phone_number %>
    </p>
    <p>
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </p>
    <p>
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :contact_mail %>
    </p>
    <p>
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </p>
    <p>
      <%= f.label :established_at %><br>
      <%= f.date_select :estanlished_at %>
    </p>
    <p>
    <%= f.select :category_id, @categories %>
    </p>
    <p>
      <%= f.collection_check_boxes(:food_ids, @foods, :id, :name) %>
    </p>

    <h3>Social Profile</h3>
    <%= f.fields_for :social_profile do |sf| %>
        <%= sf.label :facebook %>
        <%= sf.text_field :facebook %><br>
        <%= sf.label :twitter %>
        <%= sf.text_field :twitter %><br>
        <%= sf.label :instagram %>
        <%= sf.text_field :instagram %><br>
        <%= sf.label :foursquare %>
        <%= sf.text_field :foursquare %><br>

    <% end %>
    <p>
      <%= f.submit :save %>
    </p>

<% end %>

app/views/places/edit.html.erb
<h2>Edit Place</h2>
<%= @place.name%></b>
<%= render 'form' %>
<a href="/places">Back</a>

app/views/places/index.html.erb
<h2> All Places</h2><hr>

<% @places.each do |place|%>
    <tr>
      <b>Name:</b><td><a href="<%= place_path(place.id)%>"><%= place.name%></a></td><br>
      <b>Phone:</b><td><%= place.phone_number%></td><br>
     <% if current_owner.presence && current_owner.id == place.owner_id %>
      <a href="<%= edit_place_path(place.id) %>">Edit</a>
      <%= link_to "Delete", place_path(place),
                  method: :delete,
                  data: {confirm: 'Are you sure?'}  %><br><br>
    <% end %>
    </tr>
    <hr>
<% end %>
  <% if current_owner %>
  <a href="/places/new" >Add Place</a><br>
<% end %>
<%= link_to "Categories", categories_path %>

app/views/places/mine.html.erb
<h2> All Places</h2><hr>

<% @places.each do |place|%>
    <tr>
      <b>Name:</b><td><a href="<%= place_path(place.id)%>"><%= place.name%></a></td><br>
      <b>Phone:</b><td><%= place.phone_number%></td><br>
      <% if current_owner.presence && current_owner.id == place.owner_id %>
          <a href="<%= edit_place_path(place.id) %>">Edit</a>
          <%= link_to "Delete", place_path(place),
                      method: :delete,
                      data: {confirm: 'Are you sure?'}  %><br><br>
      <% end %>
    </tr>
    <hr>
<% end %>
<% if current_owner %>
    <a href="/places/new" >Add Place</a><br>
<% end %>
<%= link_to "Categories", categories_path %>

app/views/places/new.html.erb
<h2>New Place</h2>
<%= render 'form'%>
<br><br><a href="/places">Back</a>

app/views/places/show.html.erb
<b>Name:</b><td><%= @place.name%></td><br>
<b>Phone Number:</b><td><%= @place.phone_number%></td><br>
<b>Address:</b><td><%= @place.address%></td><br>
<b>City:</b><td><%= @place.city%></td><br>
<b>Category:</b><td><%= @place.category.name%></td><br>
<b>E-mail:</b><td><%= @place.contact_mail%></td><br>
<b>Established at:</b><td><%= @place.estanlished_at%></td><br>
<b>Foods:</b> <td><%= @place.foods.collect { |x| x.name }%></td><br>
<b> Facebook:</b> <%= @place.social_profile.facebook %><br>
<b> Twitter:</b> <%= @place.social_profile.twitter %><br>
<b> Instagram:</b> <%= @place.social_profile.instagram %><br>
<b> Foursquare:</b> <%= @place.social_profile.foursquare %><br>

<% @place.comments.each do |comment| %>
    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
      <% if current_customer.present? && current_customer.id == comment.customer.id %>
    <%= link_to 'Destroy Comment', [comment.place, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' } %></p>
      <% end %>
<% end %>
<p>

</p>
<% if current_customer %>
<h2>Add a comment:</h2>
<div class="panel-body">
<%= form_for([@place, @place.comments.new]) do |f| %>


    <p>
      <%= f.label :Comment  %><br>
      <%= f.text_field :body, size: 70%>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>
  <% end %>
</div>
<h1>Reservations</h1>
<% @place.reservations.each do |r| %>
        <p>
          E-mail :
          <%= r.customer.email %><br>
          Date :
          <%= r.date %><br>
          People :
          <%= r.number_of_people %>
          <% if current_customer.present? && current_customer.id == r.customer.id %>
          <%= link_to 'Destroy Reservation', [r.place, r],
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </p>
    <% end %>
<% end %>

<%= render 'reservations/form' %>

<a href="/places">Back</a>

app/views/reservations/_form.html.erb
<% if current_customer %>
<h1>Make Reservation</h1>

<%= form_for [@place, @place.reservations.build] do |f| %>
    <p>
      <%= f.label "People" %><br>
      <%=  f.text_field :number_of_people %>
    </p>
    <p>
    <p>
      <%= f.label :Date %><br>
      <%= f.date_select :date %>
    </p>

      <%= f.submit "Reservate" %>
    </p>


<% end %>
<% end %>